create table users (
	id INT,
	first_name VARCHAR(50),
	last_name VARCHAR(50),
	email VARCHAR(50),
	country VARCHAR(50),
	status INT
);
insert into users (id, first_name, last_name, email, country, status) values (1, 'Janka', 'Huburn', 'jhuburn0@yahoo.com', 'China', 1);
insert into users (id, first_name, last_name, email, country, status) values (2, 'Dirk', 'des Remedios', 'ddesremedios1@state.gov', 'Jamaica', 1);
insert into users (id, first_name, last_name, email, country, status) values (3, 'Dewie', 'Lamping', 'dlamping2@domainmarket.com', 'Sri Lanka', 0);
insert into users (id, first_name, last_name, email, country, status) values (4, 'Modesta', 'Byham', 'mbyham3@unicef.org', 'Brazil', 0);
insert into users (id, first_name, last_name, email, country, status) values (5, 'Fred', 'Castleman', 'fcastleman4@gov.uk', 'Poland', 1);
insert into users (id, first_name, last_name, email, country, status) values (6, 'Justis', 'Panner', 'jpanner5@nasa.gov', 'Bolivia', 1);
insert into users (id, first_name, last_name, email, country, status) values (7, 'Kanya', 'Clulow', 'kclulow6@yahoo.com', 'Indonesia', 1);
insert into users (id, first_name, last_name, email, country, status) values (8, 'Davita', 'Francke', 'dfrancke7@princeton.edu', 'Netherlands', 1);
insert into users (id, first_name, last_name, email, country, status) values (9, 'Dyanne', 'Hunter', 'dhunter8@deliciousdays.com', 'Thailand', 1);
insert into users (id, first_name, last_name, email, country, status) values (10, 'Amos', 'Tapton', 'atapton9@hugedomains.com', 'Indonesia', 1);
insert into users (id, first_name, last_name, email, country, status) values (11, 'Burke', 'Minter', 'bmintera@npr.org', 'Nigeria', 1);
insert into users (id, first_name, last_name, email, country, status) values (12, 'Murdock', 'Nuton', 'mnutonb@t.co', 'Israel', 0);
insert into users (id, first_name, last_name, email, country, status) values (13, 'Row', 'Pally', 'rpallyc@baidu.com', 'Canada', 0);
insert into users (id, first_name, last_name, email, country, status) values (14, 'Willi', 'Benoi', 'wbenoid@merriam-webster.com', 'China', 0);
insert into users (id, first_name, last_name, email, country, status) values (15, 'Coreen', 'Dansey', 'cdanseye@abc.net.au', 'France', 0);
insert into users (id, first_name, last_name, email, country, status) values (16, 'Roth', 'Benmore', 'rbenmoref@people.com.cn', 'Portugal', 1);
insert into users (id, first_name, last_name, email, country, status) values (17, 'Diann', 'Sambiedge', 'dsambiedgeg@studiopress.com', 'China', 1);
insert into users (id, first_name, last_name, email, country, status) values (18, 'Irina', 'de Lloyd', 'idelloydh@vkontakte.ru', 'Sweden', 0);
insert into users (id, first_name, last_name, email, country, status) values (19, 'Ogden', 'Mc Elory', 'omceloryi@bizjournals.com', 'China', 0);
insert into users (id, first_name, last_name, email, country, status) values (20, 'Aubree', 'McMeekin', 'amcmeekinj@histats.com', 'Greece', 0);
insert into users (id, first_name, last_name, email, country, status) values (21, 'Jermaine', 'Raden', 'jradenk@soundcloud.com', 'Ukraine', 0);
insert into users (id, first_name, last_name, email, country, status) values (22, 'Raviv', 'Wrout', 'rwroutl@dot.gov', 'Indonesia', 0);
insert into users (id, first_name, last_name, email, country, status) values (23, 'Peder', 'Walburn', 'pwalburnm@kickstarter.com', 'China', 1);
insert into users (id, first_name, last_name, email, country, status) values (24, 'Kassia', 'Aldersley', 'kaldersleyn@webnode.com', 'Poland', 0);
insert into users (id, first_name, last_name, email, country, status) values (25, 'Illa', 'Olivier', 'ioliviero@123-reg.co.uk', 'China', 0);
insert into users (id, first_name, last_name, email, country, status) values (26, 'Edna', 'Whiskin', 'ewhiskinp@comcast.net', 'Russia', 1);
insert into users (id, first_name, last_name, email, country, status) values (27, 'Rea', 'Jeanon', 'rjeanonq@shop-pro.jp', 'Spain', 0);
insert into users (id, first_name, last_name, email, country, status) values (28, 'Harmonia', 'Barby', 'hbarbyr@constantcontact.com', 'Vietnam', 1);
insert into users (id, first_name, last_name, email, country, status) values (29, 'Ruby', 'Tibols', 'rtibolss@liveinternet.ru', 'United States', 1);
insert into users (id, first_name, last_name, email, country, status) values (30, 'Holt', 'Powderham', 'hpowderhamt@engadget.com', 'Portugal', 1);
insert into users (id, first_name, last_name, email, country, status) values (31, 'Jacquelin', 'Warin', 'jwarinu@tinypic.com', 'China', 1);
insert into users (id, first_name, last_name, email, country, status) values (32, 'Otho', 'Diggons', 'odiggonsv@prlog.org', 'Indonesia', 1);
insert into users (id, first_name, last_name, email, country, status) values (33, 'Marven', 'Shatford', 'mshatfordw@squidoo.com', 'Russia', 1);
insert into users (id, first_name, last_name, email, country, status) values (34, 'Verile', 'Josskovitz', 'vjosskovitzx@51.la', 'Nigeria', 0);
insert into users (id, first_name, last_name, email, country, status) values (35, 'Trevor', 'Thornton-Dewhirst', 'tthorntondewhirsty@dyndns.org', 'China', 1);
insert into users (id, first_name, last_name, email, country, status) values (36, 'Chet', 'Purse', 'cpursez@printfriendly.com', 'China', 0);
insert into users (id, first_name, last_name, email, country, status) values (37, 'Silvie', 'Myott', 'smyott10@bluehost.com', 'Nigeria', 1);
insert into users (id, first_name, last_name, email, country, status) values (38, 'Vita', 'Lamerton', 'vlamerton11@ustream.tv', 'Canada', 1);
insert into users (id, first_name, last_name, email, country, status) values (39, 'Mervin', 'Mabbott', 'mmabbott12@soup.io', 'China', 1);
insert into users (id, first_name, last_name, email, country, status) values (40, 'Sisile', 'Florey', 'sflorey13@ft.com', 'Dominican Republic', 1);
insert into users (id, first_name, last_name, email, country, status) values (41, 'Malvin', 'Meegin', 'mmeegin14@purevolume.com', 'Afghanistan', 0);
insert into users (id, first_name, last_name, email, country, status) values (42, 'Madonna', 'Nowaczyk', 'mnowaczyk15@stumbleupon.com', 'China', 0);
insert into users (id, first_name, last_name, email, country, status) values (43, 'Deloris', 'Pendlington', 'dpendlington16@sakura.ne.jp', 'Ukraine', 0);
insert into users (id, first_name, last_name, email, country, status) values (44, 'Ofelia', 'Guyonneau', 'oguyonneau17@acquirethisname.com', 'Brazil', 1);
insert into users (id, first_name, last_name, email, country, status) values (45, 'Adoree', 'Blann', 'ablann18@wp.com', 'Bosnia and Herzegovina', 1);
insert into users (id, first_name, last_name, email, country, status) values (46, 'Fiona', 'Cullip', 'fcullip19@artisteer.com', 'Papua New Guinea', 1);
insert into users (id, first_name, last_name, email, country, status) values (47, 'Lavinia', 'Helversen', 'lhelversen1a@cafepress.com', 'United States', 1);
insert into users (id, first_name, last_name, email, country, status) values (48, 'Abbe', 'Kingsmill', 'akingsmill1b@google.pl', 'China', 1);
insert into users (id, first_name, last_name, email, country, status) values (49, 'Sophi', 'McVeagh', 'smcveagh1c@npr.org', 'Russia', 1);
insert into users (id, first_name, last_name, email, country, status) values (50, 'Reade', 'Chrestien', 'rchrestien1d@addtoany.com', 'China', 1);
insert into users (id, first_name, last_name, email, country, status) values (51, 'Madelyn', 'Blasio', 'mblasio1e@bing.com', 'China', 0);
insert into users (id, first_name, last_name, email, country, status) values (52, 'Rosella', 'Crosham', 'rcrosham1f@senate.gov', 'China', 0);
insert into users (id, first_name, last_name, email, country, status) values (53, 'Rodney', 'Yakovitch', 'ryakovitch1g@nydailynews.com', 'China', 1);
insert into users (id, first_name, last_name, email, country, status) values (54, 'Alf', 'Halvosen', 'ahalvosen1h@dedecms.com', 'Thailand', 1);
insert into users (id, first_name, last_name, email, country, status) values (55, 'Araldo', 'Oag', 'aoag1i@xinhuanet.com', 'Russia', 1);
insert into users (id, first_name, last_name, email, country, status) values (56, 'Ber', 'Longhurst', 'blonghurst1j@fc2.com', 'Philippines', 1);
insert into users (id, first_name, last_name, email, country, status) values (57, 'Franky', 'Connal', 'fconnal1k@clickbank.net', 'Brazil', 0);
insert into users (id, first_name, last_name, email, country, status) values (58, 'Jammie', 'Douse', 'jdouse1l@globo.com', 'Poland', 0);
insert into users (id, first_name, last_name, email, country, status) values (59, 'Fraze', 'Pendlenton', 'fpendlenton1m@biblegateway.com', 'Indonesia', 1);
insert into users (id, first_name, last_name, email, country, status) values (60, 'Sauveur', 'Romanelli', 'sromanelli1n@skyrock.com', 'France', 0);
insert into users (id, first_name, last_name, email, country, status) values (61, 'Ynez', 'Dillinger', 'ydillinger1o@berkeley.edu', 'Slovenia', 0);
insert into users (id, first_name, last_name, email, country, status) values (62, 'Chickie', 'Elfitt', 'celfitt1p@scribd.com', 'Portugal', 0);
insert into users (id, first_name, last_name, email, country, status) values (63, 'Garnet', 'Barbara', 'gbarbara1q@cpanel.net', 'Uruguay', 1);
insert into users (id, first_name, last_name, email, country, status) values (64, 'Hunter', 'Hames', 'hhames1r@issuu.com', 'Japan', 1);
insert into users (id, first_name, last_name, email, country, status) values (65, 'Karry', 'Hartman', 'khartman1s@cyberchimps.com', 'Greece', 1);
insert into users (id, first_name, last_name, email, country, status) values (66, 'Sula', 'Janzen', 'sjanzen1t@icio.us', 'Azerbaijan', 0);
insert into users (id, first_name, last_name, email, country, status) values (67, 'Donavon', 'Wilfinger', 'dwilfinger1u@blog.com', 'Marshall Islands', 0);
insert into users (id, first_name, last_name, email, country, status) values (68, 'Kalinda', 'Triplett', 'ktriplett1v@hud.gov', 'Portugal', 1);
insert into users (id, first_name, last_name, email, country, status) values (69, 'Consolata', 'Columbell', 'ccolumbell1w@surveymonkey.com', 'Dominican Republic', 0);
insert into users (id, first_name, last_name, email, country, status) values (70, 'Hilario', 'Nann', 'hnann1x@buzzfeed.com', 'Colombia', 1);
insert into users (id, first_name, last_name, email, country, status) values (71, 'Erika', 'Raittie', 'eraittie1y@answers.com', 'Indonesia', 0);
insert into users (id, first_name, last_name, email, country, status) values (72, 'Nataniel', 'Heynel', 'nheynel1z@purevolume.com', 'Ecuador', 1);
insert into users (id, first_name, last_name, email, country, status) values (73, 'Port', 'Cohalan', 'pcohalan20@google.es', 'Ukraine', 0);
insert into users (id, first_name, last_name, email, country, status) values (74, 'Ky', 'Garfirth', 'kgarfirth21@redcross.org', 'China', 0);
insert into users (id, first_name, last_name, email, country, status) values (75, 'Deborah', 'Stroband', 'dstroband22@topsy.com', 'Colombia', 0);
insert into users (id, first_name, last_name, email, country, status) values (76, 'Kev', 'Roseman', 'kroseman23@ftc.gov', 'Brazil', 1);
insert into users (id, first_name, last_name, email, country, status) values (77, 'Abrahan', 'Battelle', 'abattelle24@zimbio.com', 'Spain', 1);
insert into users (id, first_name, last_name, email, country, status) values (78, 'Katerine', 'Stammers', 'kstammers25@ted.com', 'Poland', 0);
insert into users (id, first_name, last_name, email, country, status) values (79, 'Flory', 'MacMakin', 'fmacmakin26@ucoz.com', 'United States', 0);
insert into users (id, first_name, last_name, email, country, status) values (80, 'Lissi', 'Dener', 'ldener27@cisco.com', 'Yemen', 0);
insert into users (id, first_name, last_name, email, country, status) values (81, 'Travers', 'Barta', 'tbarta28@live.com', 'Russia', 0);
insert into users (id, first_name, last_name, email, country, status) values (82, 'Jaynell', 'Jellicorse', 'jjellicorse29@delicious.com', 'Japan', 0);
insert into users (id, first_name, last_name, email, country, status) values (83, 'Waly', 'Falla', 'wfalla2a@addthis.com', 'China', 0);
insert into users (id, first_name, last_name, email, country, status) values (84, 'Laurie', 'Roos', 'lroos2b@patch.com', 'Indonesia', 0);
insert into users (id, first_name, last_name, email, country, status) values (85, 'Parker', 'Trownson', 'ptrownson2c@mit.edu', 'United States', 1);
insert into users (id, first_name, last_name, email, country, status) values (86, 'Hansiain', 'Kinnerley', 'hkinnerley2d@usa.gov', 'China', 0);
insert into users (id, first_name, last_name, email, country, status) values (87, 'Dewey', 'Vizor', 'dvizor2e@51.la', 'Indonesia', 1);
insert into users (id, first_name, last_name, email, country, status) values (88, 'Jerrine', 'Barrand', 'jbarrand2f@webs.com', 'Nigeria', 1);
insert into users (id, first_name, last_name, email, country, status) values (89, 'Evan', 'Cicetti', 'ecicetti2g@mayoclinic.com', 'Philippines', 0);
insert into users (id, first_name, last_name, email, country, status) values (90, 'Marcellina', 'Joel', 'mjoel2h@com.com', 'Portugal', 1);
insert into users (id, first_name, last_name, email, country, status) values (91, 'Dodi', 'Jodrelle', 'djodrelle2i@dedecms.com', 'Portugal', 0);
insert into users (id, first_name, last_name, email, country, status) values (92, 'Ingeberg', 'Eteen', 'ieteen2j@wikimedia.org', 'China', 0);
insert into users (id, first_name, last_name, email, country, status) values (93, 'Hillyer', 'Verny', 'hverny2k@timesonline.co.uk', 'Poland', 1);
insert into users (id, first_name, last_name, email, country, status) values (94, 'Thaddeus', 'MacTague', 'tmactague2l@g.co', 'China', 1);
insert into users (id, first_name, last_name, email, country, status) values (95, 'Donalt', 'Zappel', 'dzappel2m@flickr.com', 'Guatemala', 1);
insert into users (id, first_name, last_name, email, country, status) values (96, 'Christyna', 'Manuel', 'cmanuel2n@addthis.com', 'China', 0);
insert into users (id, first_name, last_name, email, country, status) values (97, 'Romeo', 'Mitchelmore', 'rmitchelmore2o@globo.com', 'China', 0);
insert into users (id, first_name, last_name, email, country, status) values (98, 'Oby', 'Halms', 'ohalms2p@smh.com.au', 'Palestinian Territory', 1);
insert into users (id, first_name, last_name, email, country, status) values (99, 'Ardys', 'Christol', 'achristol2q@spiegel.de', 'Ukraine', 0);
insert into users (id, first_name, last_name, email, country, status) values (100, 'Calhoun', 'Hutley', 'chutley2r@independent.co.uk', 'Philippines', 1);
